Repository wecode-bootcamp-korea/29-westagram-backend-4-team, pull requests merged in 2022-01, with the labels that each got.

#3 [이혜린] Mission1 : Django 초기 세팅
  students/hyerin/westagram/manage.py
  students/hyerin/westagram/requirements.txt
  students/hyerin/westagram/westagram/__init__.py
  students/hyerin/westagram/westagram/asgi.py
  students/hyerin/westagram/westagram/settings.py
  students/hyerin/westagram/westagram/urls.py
  students/hyerin/westagram/westagram/wsgi.py
Labels: Status: 수정 요청

#5 [다희] Mission 2: 모델링
  students/dahee/users/__init__.py
  students/dahee/users/admin.py
  students/dahee/users/apps.py
  students/dahee/users/migrations/0001_initial.py
  students/dahee/users/migrations/0002_user_created_at_user_updated_at_alter_user_email_and_more.py
  students/dahee/users/migrations/0003_alter_user_name.py
  students/dahee/users/migrations/0004_alter_user_phone_number.py
  students/dahee/users/migrations/__init__.py
  students/dahee/users/models.py
  students/dahee/users/tests.py
  students/dahee/users/views.py
  students/dahee/westagram/settings.py
Labels: 멘토 리뷰 요청

#8 [다희] Mission 3: 회원가입 기능 구현
  students/dahee/users/urls.py
  students/dahee/users/views.py
  students/dahee/westagram/urls.py
Labels: 멘토 리뷰 요청

#9 [다희] Mission 4: 로그인 기능 구현
  students/dahee/users/urls.py
  students/dahee/users/views.py
  students/dahee/westagram/urls.py
Labels: 멘토 리뷰 요청

#10 [창현] Mission 4: 로그인 기능 구현
  students/changhyeon/users/urls.py
  students/changhyeon/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#11 [창현] Misstion 5: 회원가입 비밀번호 암호화 적용
  students/changhyeon/requirements.txt
  students/changhyeon/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료

#12 [다희] Mission 5: 회원가입 비밀번호 암호화 적용
  students/dahee/requirements.txt
  students/dahee/users/views.py
Labels: 멘토 리뷰 요청, 피어 리뷰 완료
